name: checkov-action
on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform
          quiet: true
